# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rackson-five}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Holt"]
  s.date = %q{2010-03-12}
  s.description = %q{Embeds Jackson Five members into your rack based application}
  s.email = %q{ads.noob@gmail.com}
  s.extra_rdoc_files = [
    "README.mdown"
  ]
  s.files = [
    "LICENCE",
     "README.mdown",
     "Rakefile",
     "VERSION",
     "lib/rack/html/rackson-five.html",
     "lib/rack/images/group.png",
     "lib/rack/images/tile.png",
     "lib/rack/midi/want_you_back.mid",
     "lib/rack/rackson-five.rb"
  ]
  s.homepage = %q{http://github.com/omgitsads/rackson-five}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Add some Jackson 5 love to your rack based website. It's as easy as 1-2-3}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

